# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ task4 ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build
      run: mkdir 3rdparty && git clone https://github.com/google/googletest.git 3rdparty && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/runner/work/techprog/techprog .. && make && make install
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: bin/CTestExe
        report-path: /home/runner/work/techprog/techprog/
        working-directory: /home/runner/work/techprog/techprog/
    - name: UploadArtifacts
      uses: actions/upload-artifact@v1
      with:
        name: bin
        path: /home/runner/work/techprog/techprog/exe/bin/


